@startuml

title Deployment for Information System
left to right direction

node "<<Настільний комп'ютер>>" as dk {
  node "<<OS Windows>>" {
    node "<<Веб-навігатор>>" {
      component [*.js (angular)]
    }
  }
}

interface клавіатура
interface миша

клавіатура -- dk
миша -- dk

@enduml
